kind: pipeline
name: default

steps:

  - name: build
    image: drailing/go_packr_zip
    environment:
      GO111MODULE: on
    commands:
      - make build-alpine
    when:
      branch: master

  - name: dockerize
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: drailing/instatxt
      build_args: 
        - BIN_ARG=${DRONE_REPO_NAME}-${DRONE_TAG=master}-alpine
      tags:
        - '${DRONE_TAG=latest}'
    when:
      branch: master
